.TH "M2CAD.MCA" 3 "Tue Dec 1 2015" "Version 1.0" "M2CAD" \" -*- nroff -*-
.ad l
.nh
.SH NAME
M2CAD.MCA \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBmMCA\fP"
.br
.ti -1c
.RI "def \fBMOM\fP"
.br
.ti -1c
.RI "def \fBMAD\fP (x)"
.br
.ti -1c
.RI "def \fBmr_filter\fP"
.br
.ti -1c
.RI "def \fBlinorm\fP (A, nit)"
.br
.ti -1c
.RI "def \fBPCA_initialise\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "tuple \fBreweight\fP = (thmap[j,:,:,:])"
.br
.RI "\fItest \fP"
.ti -1c
.RI "tuple \fBsub\fP = (thmap[j\-1,:,:,:])"
.br
.ti -1c
.RI "int \fBweight2\fP = 1"
.br
.ti -1c
.RI "tuple \fBkthr\fP = np\&.max([kmax, k])"
.br
.ti -1c
.RI "\fBX\fP = X+S"
.br
.ti -1c
.RI "\fBk\fP = k\-step"
.br
.ti -1c
.RI "tuple \fBS\fP = np\&.zeros((ns,n1,n2))"
.br
.ti -1c
.RI "tuple \fBsig\fP = np\&.zeros((nb))"
.br
.ti -1c
.RI "int \fBserr\fP = sig+0"
.br
.ti -1c
.RI "tuple \fBerr\fP = np\&.sum((img[i,:,:]\-A[i,0]*S[0,:,:]\-A[i,1]*S[1,:,:]))"
.br
.ti -1c
.RI "tuple \fBChi\fP = np\&.sum(serr/sigma_y**2)"
.br
.ti -1c
.RI "tuple \fBth\fP = np\&.multiply(th\&.T,levels[:sh[0]])"
.br
.ti -1c
.RI "int \fBimnew\fP = 0"
.br
.ti -1c
.RI "int \fBi\fP = 0"
.br
.ti -1c
.RI "\fBR\fP = img"
.br
.ti -1c
.RI "tuple \fBalpha\fP = mw\&.wave_transform(R,lvl, newwave = 0)"
.br
.ti -1c
.RI "tuple \fBRnew\fP = mw\&.iuwt(M*alpha)"
.br
.ti -1c
.RI "tuple \fBwmap\fP = mw\&.wave_transform(imnew,lvl)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
@package M2CAD
.fi
.PP
 
.SH "Function Documentation"
.PP 
.SS "def M2CAD\&.MCA\&.linorm ( A,  nit)"

.PP
.nf
  Estimates the maximal eigen value of a matrix A

  INPUTS:
      A: matrix
      nit: number of iterations

  OUTPUTS:
      xn: maximal eigen value

   EXAMPLES
.fi
.PP
 
.SS "def M2CAD\&.MCA\&.MAD ( x)"

.PP
.nf
  Estimates noise level in an image from Median Absolute Deviation

  INPUTS:
      x: image 

  OUTPUTS:
      sigma: noise standard deviation

  EXAMPLES

.fi
.PP
 
.SS "def M2CAD\&.MCA\&.mMCA ( img,  A,  kmax,  niter,  mode = \fC'PCA'\fP,  PCA = \fC[2\fP,  harder = \fC0\fP,  pos = \fCFalse\fP,  threshmode = \fC'mom'\fP,  lvl = \fC6\fP,  soft = \fCFalse\fP,  reweighting = \fC'none'\fP)"

.PP
.nf
  mMCA runs the M2CAD algorithm over a cube of multi-band images.
  
  INPUTS:
      img: multiband cube with size nbxn1xn2 where nb is the number of bands and n1xn2,
the size of the images
      A: the mixing matrix. if mode is set to 'PCA', A will be ignored and can be set to 0
      kmax: detection threshold in units of noise standard deviation usually chosen between 3 and 5 
      niter: number of iterations of the M2CAD algorithm

  OUTPUTS:
      S: extracted sources
      A: mixing matrix, either given by the user or estimate by PCA with option mode ='PCA' 

  OPTIONS:
      mode: if set to 'PCA', the mixing matrix A will be estimated from PCA decomposition of the SEDs
      PCA: parameters for PCA sensitivity. if mode is set to 'PCA', the PCA estimator will take PCA[0]
as the number of sources to be extracted and PCA[1] as a sensitivity parameter to discriminate between
source. Values betwee 5 and 30 are usually recommended
      harder: if set to 1, 
      pos: if set to True, the output of the hard thresholding procedure is constrined to be positive
      threshmode: if set to 'mom', adaptive method of moments is used at every iteration to decrease the  threshold
      lvl: number of wavelet levels to use in the decompositions, default is 6.
      soft: if set to True, soft thresholding is used 

  EXAMPLE:
.fi
.PP
 
.SS "def M2CAD\&.MCA\&.MOM ( R,  sigma,  lvl = \fC6\fP)"

.PP
.nf
Estimates the best for a threshold from method of moments

  INPUTS:
      R: multi-sources cube with size nsxn1xn2 where ns is the number of sources
      and n1xn2, the size of an image
      sigma: noise standard deviation

  OUTPUTS:
      k: threshold level

  OPTIONS:
      lvl: number of wavelet levels used in the decomposition, default is 6.

  EXAMPLES

.fi
.PP
 
.SS "def M2CAD\&.MCA\&.mr_filter ( img,  niter,  k,  sigma,  lvl = \fC6\fP,  pos = \fCFalse\fP,  harder = \fC0\fP,  mulweight = \fC1\fP,  subweight = \fC0\fP,  addweight = \fC0\fP,  soft = \fCFalse\fP)"

.PP
.nf
  Computes wavelet iterative filtering on an image.

  INPUTS:
      img: image to be filtered
      niter: number of iterations (10 is usually recommended)
      k: threshold level in units of sigma
      sigma: noise standard deviation

  OUTPUTS:
      imnew: filtered image
      wmap: weight map

  OPTIONS:
      lvl: number of wavelet levels used in the decomposition, default is 6.
      pos: if set to True, positivity constrain is applied to the output image
      harder: if set to one, threshold levels are risen. This is used to compensate for correlated noise
      for instance
      mulweight: multiplicative weight (default is 1)
      subweight: weight map derived from other sources applied to diminish the impact of a given set of coefficient (default is 0)
      addweight: weight map used to enhance previously detected features in an iterative process (default is 0)
      soft: if set to True, soft thresholding is used
      
  EXAMPLES

.fi
.PP
 
.SS "def M2CAD\&.MCA\&.PCA_initialise ( cube,  ns,  angle = \fC15\fP,  npca = \fC64\fP)"

.PP
.nf
  Estimates the mixing matrix of of two sources in a multi band set of images

  INPUTS:
      cube: multi-band cube from which to extract mixing coefficients
      ns: number of mixed sources

  OUTPUTS:
      A0: mixing matrix

  OPTIONS:
      angle: sensitivity parameter. The angular resolution at which the algorithm has to look for PCA coefficients clustering
      npca: square root of the number of pixels to be used. Since too big images result in too big computation time
      we propose to downsample the image in order to get reasonable calculation time

  EXAMPLES

.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for M2CAD from the source code\&.
